[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --no-input"
]

[phases.setup]
nixPkgs = ["python311", "gcc"]

[start]
cmd = "bash start.sh"

[variables]
DJANGO_SETTINGS_MODULE = "coffee_lab_backend.settings"
DEBUG = "false"
ALLOWED_HOSTS = "*.up.railway.app,localhost,127.0.0.1"